### ISSUE TITLE
when github returns results, wordpress results are not shown

### ISSUE THREAD

**Issue by notslang** [pdclark/github-plugin-search#15]
I've tried like 15 queries, many of which I know return results for non-github plugins, but github plugins are the only ones shown. The only query that I found that returned wordpress.org plugins was (coincidentally) "disable". But then I didn't get any results from github.

**Comment by pdclark** [comment]
This is expected behavior. I would like to add an option to select Github or WordPress.org in the future, but as the plugin is now, it completely replaces search with Github.

**Comment by notslang** [comment]
umm... that sounds less like a feature and more like a bug.

**Comment by pdclark** [comment]
I didn't say it was a feature — I said it was expected. User Interface for switching hasn't been developed yet. 

If you'd like to see UI for it immediately, you're welcome to submit a pull request.

In the meantime, if you don't want to search Git, disable the plugin.
