### ISSUE TITLE
Bitbucket support 

### ISSUE THREAD

**Issue by krembo99** [pdclark/github-plugin-search#17]
Support also for bitbucket would be great . Lot´s of wp plugins there too..

**Comment by pdclark** [comment]
As a Bitbucket user myself, I'd also love to see this. Unfortunately, Bitbucket currently doesn't allow an API for code search (or code search on the site, for that matter). To be able to return results only for repositories that contain a WordPress plugin, Bitbucket has to allow us to search the code.

There's an open issue on this at Bitbucket. You can view it an upvote here: https://bitbucket.org/site/master/issue/2874/ability-to-search-source-code-bb-39
